language: node_js
node_js:
  - 'node' # use latest stable nodejs version
  - '7'
  - '6'

script:
  - npm test  # build and test
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
